Some fixes
kestrel1110/Navy-Campaign pull request #31
Opened 2024-09-17 09:49 UTC by TheGiraffe3

_If/when this gets merged, you should squash it._

* Fixes #23.
* Fixes #24.
* Includes some changes from #30.
* Replaces some numbers with `<payment>` (does the exact same thing).
* Fixes other dialog problems.

You probably want to find and replace all instances of `apply` with `action`; `apply` doesn't do anything but throw errors.
It would also be worth switching the player-conditions you set to be slightly more exclusive; e.g. "rudolph hines: rivalry" instead of just "rivalry". 
Also, the standard is to have a space after ellipses, and to have the letter after it be lowercase (unless of course it's a name or the word "I").
Endless Sky doesn't use Markdown, so using `*` just adds unneeded text that doesn't mean anything.

I'm sorry you didn't like the spellcheck. Did you know how to fix the errors it found?

2024-09-17 16:43 UTC, kestrel1110 commented
Changes requested:
Readme: no offence meant, but there are many contributors who are not mentioned here- that line was for those who helped massively with the intro sequences.
I like the asterisk, it can be reasonably inferred that they mean emphasis.
The other stuff is good, im gonna see if i can get this merged

2024-09-17 16:45 UTC, TheGiraffe3 commented
It's fine.

~~Not sure if you saw my comments on the other PR, those might be worth including here.~~

2024-09-17 17:01 UTC, TheGiraffe3 commented
Ready for merge when you are.

2024-09-17 17:40 UTC, kestrel1110 commented
Had to go to work, gotta finish reviewing when I get back--afterwards it should be good :)

2024-09-17 21:07 UTC, kestrel1110 requested changes
Several changes requested in comments

2024-09-17 21:07 UTC, kestrel1110 commented on data/missions.txt
> +			`	"Captain <last>, at ease," Danforth finally says as he stands up from behind his desk. "We can go over the details later in the spaceport," he adds, walking towards you. "In the meantime, here's
In some cases it is better to switch it up and not always have the raw value, and add some flair- hence this should go back- dont really know how to request the review, but that instance should go back.

2024-09-17 21:07 UTC, kestrel1110 commented on data/missions.txt
> +			`	"... worse, sir?" you ask, cautiously.`
Beginning of a sentence even though it has an ellipses...

2024-09-17 21:07 UTC, kestrel1110 commented on data/attack_outline.txt
dont delete that i need it

2024-09-17 21:07 UTC, kestrel1110 commented on data/missions.txt
> +			action
did not realise this did not work- good eye

2024-09-17 21:07 UTC, kestrel1110 commented on data/missions.txt
> +			`	Your eyes widen slightly, though you maintain your salute. "Really?"`
revert that line,

dialogue is indented, normal sentences are not- thats the general rule

2024-09-17 21:08 UTC, kestrel1110 commented on data/attack_outline.txt
as in the whole file

2024-09-17 21:10 UTC, kestrel1110 commented
Note: `I'm sorry you didn't like the spellcheck. Did you know how to fix the errors it found?`
Correct, I was not familiar with the tool so I just deleted it for my personal ease
(I don't like looking at error messages)

Unrelated, however, thank you for taking interest and contributing- it is very helpful

2024-09-18 04:49 UTC, TheGiraffe3 commented on data/missions.txt
> +			`	"Captain <last>, at ease," Danforth finally says as he stands up from behind his desk. "We can go over the details later in the spaceport," he adds, walking towards you. "In the meantime, here's
It does the exact same thing though.
`<payment>` is substituted for "[the number of credits] credits".

2024-09-18 04:50 UTC, TheGiraffe3 commented on data/missions.txt
> +			`	Your eyes widen slightly, though you maintain your salute. "Really?"`
```suggestion
			`Your eyes widen slightly, though you maintain your salute. "Really?"`
```

2024-09-18 04:51 UTC, TheGiraffe3 commented on data/missions.txt
> +			`	"... worse, sir?" you ask, cautiously.`
Unsure. I'll revert it for now.
```suggestion
			`	"... Worse, sir?" you ask, cautiously.`
```

2024-09-18 13:27 UTC, kestrel1110 commented on data/missions.txt
> +			`	"Captain <last>, at ease," Danforth finally says as he stands up from behind his desk. "We can go over the details later in the spaceport," he adds, walking towards you. "In the meantime, here's
True, but it doesn't have commas all the time does it?

2024-09-18 14:17 UTC, TheGiraffe3 commented on data/missions.txt
> +			`	"Captain <last>, at ease," Danforth finally says as he stands up from behind his desk. "We can go over the details later in the spaceport," he adds, walking towards you. "In the meantime, here's
How do you mean?

Seeing as how there is no real change to the player, I'm not sure this is a problem - it just makes it easier if the payment changes later.

2024-09-18 14:25 UTC, TheGiraffe3 commented
Resolved conflicts.

2024-09-18 14:28 UTC, TheGiraffe3 commented on data/missions.txt
> +			`	"That's the other reason I brought you here, <last>," he adds while the two of you exit the Stardust. "I wanted to make it clear that just because I have a higher rank, that does not mean I shou
```suggestion
			`	"That's the other reason I brought you here, <last>," he adds while the two of you exit the pub. "I wanted to make it clear that just because I have a higher rank, that does *not* mean I should also feel superior to you. We're both humans, and on that note, equals. I'm sure my actions have proved as much, but my position does *not* give me the right to treat you like dirt, and any Admiral who tells you otherwise is either delusional, drunk, a liar or an idiot. Or all of the above."`
```

2024-09-18 14:30 UTC, kestrel1110 commented on data/missions.txt
> +			`	"Captain <last>, at ease," Danforth finally says as he stands up from behind his desk. "We can go over the details later in the spaceport," he adds, walking towards you. "In the meantime, here's
The payment method pulls the raw number
So 25000
Vs
25,000

2024-09-18 14:31 UTC, TheGiraffe3 commented on data/missions.txt
> +			`	"Captain <last>, at ease," Danforth finally says as he stands up from behind his desk. "We can go over the details later in the spaceport," he adds, walking towards you. "In the meantime, here's
No, it doesn't. It'll look exactly the same from a player perspective.

2024-09-18 14:32 UTC, kestrel1110 approved these changes

2024-09-18 14:33 UTC, merged